export {default as Navbar} from './Navbar'
export {default as Searchbar} from './Searchbar'
export {default as Home} from './Home'
export {default as Properties} from './Properties'
export {default as Team} from './Team'
export {default as Contact} from './Contact'